name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to Pew Pew Penguino Assets! Thanks for making your first issue. Please make sure you've tagged your issue!"
        pr-message: "Wow! You made a pull request on Pew Pew Penguino Assets. We'll hopefully merge it soon!"
